spring:
  datasource:
    url: jdbc:postgresql://toyple-db.cgha9ef7axpa.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      default_schema: prop-tech
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect